# Generated by Django 4.1.13 on 2023-12-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='venues',
            new_name='Venue',
        ),
    ]
