# Generated by Django 4.1.13 on 2024-02-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_uservendor'),
        ('venue', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.usercustomer'),
            preserve_default=False,
        ),
    ]
