# Generated by Django 4.1.13 on 2024-01-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_rename_venues_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(default='1234567890', max_length=100),
        ),
    ]
