# Generated by Django 4.1.13 on 2024-01-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_venue_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
