# Generated by Django 4.1.13 on 2024-02-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_uservendor'),
        ('venue', '0004_rename_address_booking_eventname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.uservendor'),
            preserve_default=False,
        ),
    ]
