# Generated by Django 4.1.13 on 2024-03-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_venue_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='Venuename',
        ),
    ]
