# Generated by Django 4.1.13 on 2024-03-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_rename_name_venue_venuename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='username',
            new_name='vendor_id',
        ),
    ]
