# Generated by Django 4.0.1 on 2024-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_rename_venuename_venue_venuename'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
