# Generated by Django 4.0.1 on 2024-05-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_booking_amount_booking_token_booking_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Hotel', 'Hotel'), ('Cafe', 'Cafe'), ('Club', 'Club'), ('Resort', 'Resort'), ('Banquet Hall', 'Banquet Hall')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
