# Generated by Django 4.0.1 on 2024-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_venue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Banquet Hall', 'Banquet Hall')], max_length=50),
        ),
    ]
