# Generated by Django 4.0.1 on 2024-04-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_room_remove_rooms_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
