# Generated by Django 4.0.1 on 2024-05-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
