# Generated by Django 4.1.13 on 2023-12-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustomer',
        ),
    ]
