# Generated by Django 4.0.1 on 2024-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_uservendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='dp_img',
            field=models.ImageField(default='images/default_dp.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='uservendor',
            name='dp_img',
            field=models.ImageField(default='images/default_dp.png', upload_to='images/'),
        ),
    ]
